# Generated by Django 4.0.6 on 2023-05-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_rename_str_date_date_strdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='strdate',
            field=models.CharField(default='2023-05-11', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='str_date',
            field=models.CharField(default='2023-05-11', max_length=30),
        ),
    ]
