# Generated by Django 4.0.6 on 2023-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_date_strdate_alter_todo_str_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
        migrations.AlterField(
            model_name='date',
            name='strdate',
            field=models.CharField(default='2023-05-14', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='str_date',
            field=models.CharField(default='2023-05-14', max_length=30),
        ),
    ]
