# Generated by Django 4.0.6 on 2023-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='xcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
