# Generated by Django 4.0.6 on 2023-05-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_important_todo_xcompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='xcompleted',
            new_name='completed',
        ),
    ]
