# Generated by Django 4.0.6 on 2023-05-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_date_todo_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='str_date',
            field=models.CharField(default='2023-05-08', max_length=30),
        ),
    ]
